### PR TITLE
Make piglins only lose health while unzombified

### PR DESCRIPTION
**Pull request by Dual-Iron**
More consistent with vanilla zombified piglins.

### CODE REVIEW

**Comment by MoriyaShiine** [comment]
I chose to not include this for balance reasons, as Piglins already gain a power boost when outside of the nether (immunity to poison and fire for example) and I don't want them to be too powerful.

**Comment by Dual-Iron** [comment]
The slowness 2 is a rather extreme debuff. They are considered undead and fire immune in the overworld, but that also means they cannot benefit from regeneration effects. When combined with other origins (e.g. using the second_layer origin), the health reduction becomes extremely detrimental. This all adds up to make overworld piglins weirdly weak and frail.

If you still think ziglins are too strong in the overworld, you can retain consistency by giving them 10 hearts, but making them unable to swim, like actual undead. This works well in [Requiem](https://github.com/Ladysnake/Requiem/issues/313).

**Comment by Dual-Iron** [comment]
...I don't think I can PR such a thing feasibly from a Chromebook though.

**Comment by MoriyaShiine** [comment]
I see, I'll look into it.

And haha don't worry, you don't need to pr something that large especially from a Chromebook. I can add it once I decide what to do. I'm working on an update right now so it shouldn't take too long.

**Pull request closed without merging**
