### PR TITLE
Make Truffle/Magic Spores data driven

### PR DESCRIPTION
**Pull request by MerchantPug**
### Magic Spores (Cardinal Component)
- No longer stores the selected form in a unique Cardinal Component, now stores it in the player NBT relating to the power (via Apoli).
- The Cardinal Component is still there for backwards compatibility. This will change the player's MagicSporesComponent to "Converted" upon detecting a magic spores power and will run the action of the target spore.
- Moved the enum for the Cardinal Component to the new enum's class.

### Magic Spores (Power Type)
- Now works with different keybinds (specified in the power json).
- Added `sprite_location` (defaults to Truffle's gui texture) field. This specifies the texture of the radial menu.
- Added `right_action`, `up_action`, `left_action` fields. They are entity actions that execute when swapping between forms. If these aren't specified, swapping to them will be disabled. (You can always specify `origins:nothing` if you're using conditions for your functionality.)
- Added `lost_action` field, this executes when the power is lost.
  - I'm aware you can do the above with an `origins:action_on_callback` power but it's preferable that the power type has this built in imo.
- Added `swap_time` field, this configures the swap time between the forms within the radial menu.
- Added `default` field, this configures what the default option for the radial menu is. Can be `UP`, `LEFT`, `RIGHT`, `MOBILITY`, `OFFENSE`, `DEFENSE` or `NONE`. (Can be lowercase too) (None is more for datapackers than it is for Truffle). The respective truffle options are the exact same as their directional counterparts.
- Added `store_option` field.  This is a boolean that tells you whether the power type should store your current option (defaults to true) 
- Now compatible with other `extraorigins:magic_spores` powers. If both of their keybinds are held, it will prioritise one of them.

### Truffle
- Truffle Spore Swap sound no longer has randomised pitch (due to using `origins:play_sound`).
- Action fields now grant and revoke powers alongside playing the swap sound.
- Now has `extraorigins:offense_spore`, `extraorigins:defense_spore` and `extraorigins:mobility_spore` powers. These are multiple powers that include all of the Truffle stuff.
  - You could always have the powers on the Truffle too and add conditions to them.
- Moved damage taken modifiers to `origins:modify_damage_taken` power.
- Moved Air Strafe Speed to a new power type. `extraorigins:modify_air_strafe_speed`.

### Modify Air Strafe Speed
- Is a basic attribute modifier power (having `modifier` and `modifiers` fields).
- Moved functionality from the component's tick method to LivingEntityMixin's tick method.

### Magic Spores Mode (Entity Condition)
(This one may break with existing datapacks)
- No longer checks for the cardinal component.
- `mode` field is now an enum value of `UP`, `LEFT`, `RIGHT`, `MOBILITY`, `OFFENSE`, `DEFENSE` or `NONE`. (can be lowercase too).
- Added `power` field, this is a mandatory field that decides what power to check.

### Truffle Particles
- Included in the multiple powers as an `origins:simple`. This is so datapackers can add the individual particle power to their origins. I didn't use the `origins:particle` power type as it was not configurable to recreate Truffle's particles how they are right now. Feel free to (or get me to) add an `extraorigins:particle` power type.
- The particles have been moved to a tick function inside LivingEntityMixin.
  - I'd check this if anything, I just have a feeling that it's potentially unoptimised.

### Bonus FYI
- If your spore has been converted and you try logging back in on an older version, you will get Invalid Player Data. I'm actually unsure how to delete Cardinal Components from the player which is why I'm using this method. If you know how to remove a cardinal component from a player, please tell me.

### CODE REVIEW

**Comment by MerchantPug** [comment]
Converted to draft while I fix an issue with the rooted power json

**Comment by MoriyaShiine** [comment]
Looks good! I might change some things after the fact but the only required change I ask is that you remove the backwards compatibility related code; 1.18.2 will break anyways so it's not required

**Comment by MerchantPug** [comment]
Sorry for the late response, I'll get to working on it in a little bit.

**Comment by MerchantPug** [comment]
I have now removed the backwards compat.

Players will now have to put up with being swapped to mobility mode after downloading the update on old worlds.

**Pull request merged**
