### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by Snapshotlight**
Fix some mistakes in previous translation.
Simplify previous expression to make it easier to understand.
Replace the translations of two origins (floran and inchling) and some powers.

### CODE REVIEW

**Comment by MoriyaShiine** [comment]
There have been a lot of changes to the lang file, please check them

**Comment by Snapshotlight** [comment]
@MoriyaShiine These changes do not change the meaning. Just make them close to the native and more readable.

**Comment by MoriyaShiine** [comment]
Some of the powers straight up work differently than before so I don't think the meanings are the same regardless of language. I also tested using a translator, which isn't perfect but very much shows that the existing text in your fork does not accurately describe the powers

**Comment by Snapshotlight** [comment]
Fine. Sorry for not checking new changes in lang file. I will review my translation.

**Comment by Snapshotlight** [comment]
Well now it may be good.

**Pull request merged**
